spring:
  datasource:
    url: jdbc:mysql://localhost:3307/filmes_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true